### PR TITLE
Fix Windows XP build 

### PR DESCRIPTION
**Pull request by UnrealKaraulov**
This can fix Windows XP build ?

### CODE REVIEW

**Comment by UnrealKaraulov** [comment]
@kernelwernel 

Fixed:

1. __has_cpp_attribute cause error while build
2. versionhelpers.h not found in Windows 7 SDK
3. objbase.h cause error while build if not force define IUnknown
4. #include <winevt.h> not found in WIN XP

Now I can build it in Visual Studio 2022 for Windows XP (v141_xp)

**Comment by UnrealKaraulov** [comment]
I got 'VVM DETECTED' 'HyperVisor' when build for WinXP, i can't fix it :(

**Comment by UnrealKaraulov** [comment]
image
image

**Comment by kernelwernel** [comment]
> I got 'VVM DETECTED' 'HyperVisor' when build for WinXP, i can't fix it :(

sorry but I'm not sure what you mean. Did the lib detect Hyper-V under WinXP?

Also thanks for the PR! But I want to make sure what I'm merging works fine, so I'll merge it later after testing it around

**Comment by kernelwernel** [comment]
> > I got 'VVM DETECTED' 'HyperVisor' when build for WinXP, i can't fix it :(
> 
> sorry but I'm not sure what you mean. Did the lib detect Hyper-V under WinXP?

@UnrealKaraulov

**Comment by UnrealKaraulov** [comment]
@kernelwernel I run WinXP build under clean Windows 11 and got result "vm == 100% , Microsoft Hyper-V"

**Comment by kernelwernel** [comment]
> @kernelwernel I run WinXP build under clean Windows 11 and got result "vm == 100% , Microsoft Hyper-V"

did you receive any information about which techniques were detected?

**Comment by UnrealKaraulov** [comment]
> > @kernelwernel I run WinXP build under clean Windows 11 and got result "vm == 100% , Microsoft Hyper-V"
> 
> did you receive any information about which techniques were detected?

How I can get this information?

**Comment by kernelwernel** [comment]
> > > @kernelwernel I run WinXP build under clean Windows 11 and got result "vm == 100% , Microsoft Hyper-V"
> > 
> > 
> > did you receive any information about which techniques were detected?
> 
> How I can get this information?

maybe you can compile the cli.cpp file on your build, I never compiled anything for Windows XP so I'm really not sure how that would work out. If you can't, I could create another custom debug binary for you like last time

**Comment by UnrealKaraulov** [comment]
@kernelwernel I don't know how to compile cli for XP

**Comment by kernelwernel** [comment]
Is it possible if you can run either one of these and tell me the output? Would be very helpful, thanks :)

32-bit: https://github.com/kernelwernel/VMAware/actions/runs/10861852604/artifacts/1933007774
64-bit: https://github.com/kernelwernel/VMAware/actions/runs/10861852604/artifacts/1933004472

@UnrealKaraulov

**Comment by UnrealKaraulov** [comment]
image
[32bitlog.txt](https://github.com/user-attachments/files/17005545/32bitlog.txt)
[64bitlog.txt](https://github.com/user-attachments/files/17005546/64bitlog.txt)

Normal result, no VM found. But compiled not for XP (for Major version 6 Minor version 0)

**Comment by UnrealKaraulov** [comment]
For Windows XP compile possible need to changes in project settings

( for Visual Studio I add '/Zc:strictStrings-' for remove strictStrings compiler option else compile cause error BSTR )

**Comment by kernelwernel** [comment]
> For Windows XP compile possible need to changes in project settings
> 
> ( for Visual Studio I add '/Zc:strictStrings-' for remove strictStrings compiler option else compile cause error BSTR )

Hm. Do you think the errors could be fixable by a few changes to the lib? If there's like a billion errors then I'll probably just add a note in the README that says "add '/Zc:strictStrings-'  to your compiler options if you're compiling on Windows XP". 

I'm not sure how many errors you got, or more importantly WHERE the errors are located, but if it sounds realistic to find a complete fix without having to add that compiler option  then I'm definitely willing to find a solution.

**Comment by kernelwernel** [comment]
@UnrealKaraulov Is it ok if I merge the PR? I don't want this to be forgotten and left without anything out of it. If you think it's not a good idea yet then let me know.

**Comment by NotRequiem** [comment]
Hi UnrealKaraulov!

We will not support Windows XP, an operating system developed 23 years ago, because it lacks security updates and stability, making proper virtual machine detection unreliable and slowing down the process of updating this project, as we would have to test all the new detections in those systems. We encourage users to update to current Windows versions to benefit from improved functionality and full compatibility with our detection library.

However, our library is open-source, meaning that you can modify it as you want for your own purposes, and still add VM support for any old OS that you want!

The Microsoft Hyper-V false flag that you got by that time has been already fixed.

**Pull request closed without merging**
